#main.yml
name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm install